CREATE TABLE IF NOT EXISTS `sample` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'コメント',
  `c1` VARCHAR(255) NOT NULL DEFAULT 'hoge' UNIQUE COMMENT 'コメント'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'コメント';